from datetime import datetime, timezone
from functools import partial
from hashlib import shake_128
import itertools
from multiprocessing import Pool, Lock, Manager
import os
import signal
import subprocess
from types import ModuleType
import warnings

import numpy as np
import pandas as pd
try:
    from tqdm import tqdm
except ImportError:
    def tqdm(iterable, *_, **__):
        return iterable
try:
    import netCDF4
except ImportError:
    netCDF4 = None

from . import __version__
from .io import Hyrolight6Input
from .utils import sizeof_fmt, get_dtype, init_he60_output_directories
from .constants import HE60_ROOT, HE60_EXE, HE60_DATA


# %% -- Generate LUT -- %% #

def estimate_lut_size(dimensions: dict):
    ndims = [d if isinstance(d, int) else len(d) for d in dimensions.values()]
    size_bytes = np.prod(ndims) * 4  # float32
    return sizeof_fmt(size_bytes)


def make_lut(df: pd.DataFrame, varname: str = 'KLu'):
    """
    Build n-dimensional lookup table from HydroLight6 output dataframe
    :return:
    """

    # Find dimensions
    wl = np.unique(np.stack(df['wl'].to_list()), axis=0)
    if len(wl) > 1:
        raise ValueError('Multiple wavelength configurations found, cannot build LUT.')
    dims = {'wl': np.squeeze(wl)}
    if 'z' in df.columns:
        z = np.unique(np.stack(df['z'].to_list()), axis=0)
        if len(z) > 1:
            raise ValueError('Multiple depth configurations found, cannot build LUT.')
        dims['z'] = np.squeeze(z)
    ignore_dims = ['ref', varname] + list(dims.keys())
    constants = {}
    for c in df.columns:
        if c in ignore_dims:
            continue
        unique_values = df[c].unique().tolist()
        if len(unique_values) > 1:
            dims[c] = sorted(unique_values)
        else:
            constants[c] = unique_values[0]
    # Initialize LUT (check fits in memory)
    ndims = [len(d) for d in dims.values()]
    if np.prod(ndims) * 4 > 32 * 1024 **3:
        raise MemoryError(f"Lookup table size {sizeof_fmt(np.product(ndims) * 4)} exceeds 32 GB limit.")
    lut = np.empty(ndims, dtype=np.float32) * np.nan
    # Fill LUT
    main_idx = [slice(None), slice(None)] if 'z' in dims else [slice(None)]
    for _, row in df.iterrows():
        idx = main_idx + [dim.index(row[key]) for key, dim in dims.items() if key not in ['wl', 'z']]
        lut[tuple(idx)] = row[varname]
    return lut, dims, constants


# %% -- OneShot LUT Generation -- %% #

def make_lut_oneshot(varname: str, dimensions: dict, constants: dict = None,
                     path_to_lut: str = None, working_dir: str = HE60_DATA, force: bool=False):
    """
    Generate HydroLight6 input files, run HydroLight6, and build n-dimensional lookup table in NetCDF file.
    Erase input and output files from HydroLight6 as it runs.
    If ram disk is available, it's recommended to use it as working directory for speed.

    :param varname: Variable name to store in LUT (e.g. KLu, Rrs, Lu, Ed, Kd)
    :param dimensions: Environmental parameters to vary
    :param constants: Constant environmental parameters, to change defaults from Hyrolight6Input
    :param path_to_lut: Path to output NetCDF LUT file
    :param working_dir: Path to HydroLight6 working directory (default to HE60_DATA)
    :param force: Enable if resuming processing of an incomplete LUT to overwrite existing entries,
                  Recommended to True on first run and False when resuming
    :return:
    """
    if not isinstance(netCDF4, ModuleType):
        raise ModuleNotFoundError('write_netcdf requires the module netCDF4.')

    # Run UID
    lut_hash = shake_128((str(dimensions)+str(constants)).encode()).hexdigest(3)

    # Generate Input
    if constants is not None:
        for k in constants.keys():
            if k in dimensions:
                raise ValueError(f'Constants and dimensions overlap on key: {k}')
    inputs, indexes = [], []
    combinations = list(itertools.product(*dimensions.values()))
    for input in tqdm(combinations, desc='Inputs'):
        inputs.append({k: i for k, i in zip(dimensions, input)})
        indexes.append(tuple(v.index(i) for v, i in zip(dimensions.values(), input)))

    # Initialize LUT
    if force or not os.path.isfile(path_to_lut):
        with netCDF4.Dataset(path_to_lut, 'w', format='NETCDF4') as d:
            # Global attributes
            d.title = f'Lookup Table of {varname} for case 1 waters generated by HydroLight6'
            d.description = 'Source code is the documentation.'
            d.conventions = 'CF-1.10,ACDD-1.3'
            d.id = f'he60_lut_{varname.lower()}_case1.{lut_hash}'
            d.naming_authority = 'HyperNavProjectOffice'
            d.source = 'HydroLight 6.0.1'
            d.date_created = f"{datetime.now().astimezone(timezone.utc).isoformat(timespec='seconds')}"
            d.product_version = __version__
            d.varname = varname
            # Constants
            constants0 = Hyrolight6Input().__dict__
            if constants is not None:
                constants0.update(constants)
            for k in ['output_depths', 'output_dir', 'wavelength_start', 'wavelength_stop', 'wavelength_step'] + list(dimensions.keys()):
                del constants0[k]
            for k, v in constants0.items():
                dtype, fill_value = get_dtype(v)
                var = d.createVariable(k, dtype, fill_value=fill_value)
                var[...] = v
            # Dimensions
            for k, v in dimensions.items():
                d.createDimension(k, len(v))
                dtype, fill_value = get_dtype(v)
                var = d.createVariable(k, dtype, (k,), fill_value=fill_value)
                var[:] = v

    # Create input & output directories
    os.makedirs(os.path.join(working_dir, 'run', 'batch'), exist_ok=True)
    init_he60_output_directories(os.path.join(working_dir, 'output'))

    # Loop over inputs in parallel
    with Manager() as manager:
        lut_lock = manager.Lock()  # proxy lock: safe to pass under spawned processes
        stop_event = manager.Event()
        worker = partial(
            _make_lut_oneshot_runner,
            constants=constants,
            varname=varname,
            path_to_lut=path_to_lut,
            lut_lock=lut_lock,
            lut_hash=lut_hash,
            working_dir=working_dir,
            force=force
        )
        with Pool(initializer=_init_worker_ignore_sigint) as pool:  # default to os.process_cpu_count()
            try:
                for _ in tqdm(pool.imap(worker, zip(inputs, indexes)), total=len(inputs), desc=f'HE60'):
                    if stop_event.is_set():
                        break
            except KeyboardInterrupt:
                print('KeyboardInterrupt received, terminating workers...')
                stop_event.set()
                pool.terminate()  # force unblock workers waiting on the manager lock
        if stop_event.is_set():
            print('Workers terminated early, incomplete LUT at:', path_to_lut)
        else:
            print('LUT generation completed:', path_to_lut)

    # Debug Single thread
    # _make_lut_oneshot_runner((inputs[0], indexes[0]), constants, varname, path_to_lut,
    #                          Lock(), lut_hash, working_dir, force)


def _init_worker_ignore_sigint() -> None:
    # Prevent workers from printing KeyboardInterrupt tracebacks.
    # Parent process handles Ctrl+C and terminates the pool.
    signal.signal(signal.SIGINT, signal.SIG_IGN)


def _make_lut_oneshot_runner(cfg: tuple, constants: dict, varname: str, path_to_lut: str, lut_lock: Lock,
                             lut_hash: str, working_dir: str = HE60_DATA, force: bool=False):
    """
    Generate HydroLight6 input files, run HydroLight6, and append output to lut.

    Erase input and output files from HydroLight6 as it runs.
    if ram disk is available, it's recommended to use it as working directory for speed.

    :param varname:
    :param dimensions:
    :param defaults:
    :param working_dir:
    :return:
    """

    # Split config (needed as Pool.imap only supports single argument functions)
    input, index = cfg

    # Check if already processed
    if not force:
        with lut_lock:
            with netCDF4.Dataset(path_to_lut, 'r') as d:
                if varname in d.variables:
                    var = d.variables[varname]
                    if not np.ma.getmaskarray(var[(slice(None), slice(None)) + index]).all():
                        # Already processed
                        return

    # Write input file (assume directories exist)
    i = Hyrolight6Input(**input, **constants)
    i.output_dir = os.path.join(working_dir, 'output')
    input_filename = i.write(os.path.join(working_dir, 'run', 'batch'), prefix=lut_hash)

    # Run Hydrolight6
    with open(input_filename, 'r') as f:
        subprocess.run([f"./{HE60_EXE}"], stdin=f, cwd=HE60_ROOT, stdout=subprocess.DEVNULL)

    # Read output file
    output_filename = os.path.join(working_dir, 'output', 'Hydrolight', 'excel', f'M{os.path.basename(input_filename).lstrip("I").rstrip(".txt")}.xlsx')
    with warnings.catch_warnings(record=True):
        warnings.simplefilter("always")
        xlsx = pd.ExcelFile(output_filename)
        df = pd.read_excel(xlsx, varname, header=3, index_col=0)

    # Write output to LUT
    #   assume input and index are consistent with LUT dimensions
    with lut_lock:
        with netCDF4.Dataset(path_to_lut, 'a') as d:
            if varname not in d.variables:
                # Initialize output dimensions if needed
                if 'wl' not in d.dimensions:
                    # Add wavelength dimension
                    wl = df.index.to_numpy(int)
                    d.createDimension('wavelength', len(wl))
                    var = d.createVariable('wavelength', 'u2', ('wavelength',))
                    var[:] = wl
                if 'depth' not in d.dimensions:
                    # Add depth dimension
                    z = df.rename(columns={'in air': -1111}).columns.to_numpy(float)
                    d.createDimension('depth', len(z))
                    var = d.createVariable('depth', 'f4', ('depth',), fill_value=np.nan)
                    var[:] = z
                # Initialize LUT
                dimensions = tuple(['wavelength', 'depth'] + list(input.keys()))
                dimensions_sizes = tuple([d.dimensions[k].size for k in dimensions])
                var = d.createVariable(varname, 'f4', dimensions, fill_value=np.nan)
                var[:] = np.empty(dimensions_sizes, dtype = np.float32) * np.nan
            # Write data
            var = d.variables[varname]
            var[(slice(None), slice(None)) + index] = df.to_numpy(dtype=np.float32)

    # Delete input and output files
    os.remove(input_filename)
    os.remove(output_filename)
    os.remove(output_filename.rstrip('.xlsx') + '.txt')
    os.remove(os.path.join(working_dir, 'output', 'Hydrolight', 'printout', f'P{os.path.basename(input_filename).lstrip("I")}'))


# %% -- Read & Write LUT -- %% #

def write_lut(lut: np.ndarray, dims: dict, constants: dict, varname: str, filename: str):
    """
    Write n-dimensional lookup table to NetCDF file

    :param lut: lookup table
    :param dims: dimensions
    :param filename: output filename
    :return:
    """
    if not isinstance(netCDF4, ModuleType):
        raise ModuleNotFoundError('write_netcdf requires the module netCDF4.')

    with netCDF4.Dataset(filename, 'w', format='NETCDF4') as d:
        # Global attributes
        d.title = f'Lookup Table of {varname} for case 1 waters generated by HydroLight6'
        d.description = 'Source code is the documentation.'
        d.conventions = 'CF-1.10,ACDD-1.3'
        d.id = f'he60_lut_{varname.lower()}_case1'
        d.naming_authority = 'HyperNavProjectOffice'
        d.source = 'HydroLight 6.0.1'
        d.date_created = f"{datetime.now().astimezone(timezone.utc).isoformat(timespec='seconds')}"
        d.product_version = __version__
        d.varname = varname

        # Constants
        for k, v in constants.items():
            dtype, fill_value = get_dtype(v)
            var = d.createVariable(k, dtype, fill_value=fill_value)
            var[...] = v

        # Dimensions
        for k, v in dims.items():
            d.createDimension(k, len(v))
            dtype, fill_value = get_dtype(v)
            var = d.createVariable(k, dtype, (k,), fill_value=fill_value)
            var[:] = v

        # LUT
        fill_value = np.nan if np.issubdtype(lut.dtype, np.floating) else None
        var = d.createVariable(varname, lut.dtype, tuple(dims.keys()), fill_value=fill_value)
        var[:] = lut


def read_lut(filename: str):
    """
    Read n-dimensional lookup table from NetCDF file

    :param filename: input filename
    :return: lut, dims, constants
    """
    if not isinstance(netCDF4, ModuleType):
        raise ModuleNotFoundError('read_netcdf requires the module netCDF4.')

    with netCDF4.Dataset(filename, 'r') as d:
        d.set_auto_mask(False)
        varname = d.varname
        # Constants
        constants = {}
        for k in d.variables.keys():
            if k == varname or k in d.dimensions:
                continue
            constants[k] = np.asarray(d.variables[k][:]).item()
            if d.variables[k].dtype == 'u1':
                constants[k] = bool(constants[k])
        # Dimensions
        dims = {}
        for dim_name in d.dimensions.keys():
            dims[dim_name] = d.variables[dim_name][:]
        # LUT
        lut = d.variables[varname][:]

    return lut, dims, constants
