[project]
name = "pyhe60"
version = "0.2.2"
description = "Python interface for HydroLight EcoLight 6.0. Requires HydroLight EcoLight license."
license = { text = "MIT" }
readme = "README.md"
authors = [
    { name = "Nils Haëntjens", email = "nils.haentjens@maine.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
]

[project.optional-dependencies]
lut = [
    "netcdf4>=1.7.4",
    "tqdm>=4.67.3",
]
plot = [
    "kaleido>=1.2.0",
    "plotly>=6.5.2",
]
distributed = [
    "ray[default]>=2.53.0",
]

[tool.uv.build-backend]
module-name = "pyhe60"
module-root = "src"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
