from datetime import datetime, timezone
from hashlib import shake_128
import os
import shutil
import tempfile
from types import ModuleType
from typing import Tuple, List, Union

import numpy as np
import pandas as pd
try:
    import netCDF4
except ImportError:
    netCDF4 = None

from .. import __version__
from ..io import Hyrolight6Input
from ..utils import get_dtype, delay_sigint


def init_lut(path_to_lut: str, varnames: Union[str, List[str]], dimensions: dict, constants: dict, lut_hash: str = None):
    """
    Initialize LUT NetCDF file with dimensions and constants.
    The main variable is not initialized (as required knowledge from HE60 output).

    :param path_to_lut:
    :param varnames:
    :param dimensions:
    :param constants:
    :param lut_hash:
    :return:
    """
    if not isinstance(netCDF4, ModuleType):
        raise ModuleNotFoundError('write_netcdf requires the module netCDF4.')

    if os.path.isfile(path_to_lut):
        raise ValueError(f'LUT file already exists: {path_to_lut}')

    if lut_hash is None:
        lut_hash = shake_128((str(dimensions)+str(constants)).encode()).hexdigest(3)

    if isinstance(varnames, str):
        varnames = [v.strip() for v in varnames.split(',')] if ',' in varnames else [varnames]

    with delay_sigint():
        with netCDF4.Dataset(path_to_lut, 'w', format='NETCDF4') as d:
            # Global attributes
            d.title = f'Lookup Table of {varnames} for case 1 waters generated by HydroLight6'
            d.description = 'Source code is the documentation.'
            d.conventions = 'CF-1.10,ACDD-1.3'
            d.id = f'he60_lut_{"-".join([v.lower() for v in varnames])}_case1.{lut_hash}'
            d.naming_authority = 'HyperNavProjectOffice'
            d.source = 'HydroLight 6.0.1'
            d.date_created = f"{datetime.now().astimezone(timezone.utc).isoformat(timespec='seconds')}"
            d.product_version = __version__
            d.varnames = ','.join(varnames)

            # Constants
            constants0 = Hyrolight6Input().__dict__
            if constants is not None:
                constants0.update(constants)
            for k in ['output_depths', 'output_dir', 'wavelength_start', 'wavelength_stop', 'wavelength_step'] + list(
                    dimensions.keys()):
                del constants0[k]
            for k, v in constants0.items():
                dtype, fill_value = get_dtype(v)
                var = d.createVariable(k, dtype, fill_value=fill_value)
                var[...] = v

            # Dimensions
            for k, v in dimensions.items():
                d.createDimension(k, len(v))
                dtype, fill_value = get_dtype(v)
                var = d.createVariable(k, dtype, (k,), fill_value=fill_value)
                var[:] = v


def write_chunk_to_lut(dfs: Union[pd.DataFrame, List[pd.DataFrame]], index: Tuple[int],
                       varnames: Union[str, List[str]], path_to_lut: str):
    """
    Write output of one HydroLight 6.0 simulation to LUT. Assumes chunk is consistent with LUT dimensions and index.
    Automatically initialize wavelength and depth dimensions if not already present in LUT.
    Initialize LUT variable if not already present, otherwise will write to existing variable.
    Protect critical section from KeyboardInterrupt to prevent data corruption.

    :param dfs: list of DataFrame with output variable, indexed by wavelength and depth
    :param index: LUT index corresponding to the input configuration of dfs (all dfs must have the same index)
    :param varnames: variables names to write in LUT
    :param path_to_lut: path to LUT NetCDF file
    :return:
    """
    if isinstance(varnames, str):
        varnames = [v.strip() for v in varnames.split(',')] if ',' in varnames else [varnames]
    if isinstance(dfs, pd.DataFrame):
        dfs = [dfs]
    if len(dfs) != len(varnames):
        raise ValueError('Length of dfs and varnames must be the same.')

    # Get depth dimension(s)
    depthk_vars = {'Kd', 'Ku', 'KLu'}
    depth0_vars = {'Lu', 'Eod', 'Eou', 'Eo', 'Ed', 'Eu', 'Lu over Ed', 'R'}
    sv = set(varnames)
    needs_depthK = bool(depthk_vars & sv)
    needs_depth0 = bool(depth0_vars & sv)
    use_generic_depth = not (needs_depthK and needs_depth0)
    var_to_depth_dim = {}
    for varname in varnames:
        if use_generic_depth:
            var_to_depth_dim[varname] = 'depth'
        elif varname in depthk_vars:
            var_to_depth_dim[varname] = 'depthK'
        elif varname in depth0_vars:
            var_to_depth_dim[varname] = 'depth0'
        else:
            raise ValueError(f'varname {varname} not supported')

    with delay_sigint():
        with netCDF4.Dataset(path_to_lut, 'a') as d:
            # Initialize output dimensions if needed
            df = dfs[0]
            if 'wavelength' not in d.dimensions:
                # Add wavelength dimension
                wl = df.index.to_numpy(int)
                d.createDimension('wavelength', len(wl))
                var = d.createVariable('wavelength', 'u2', ('wavelength',))
                var[:] = wl
            for varname, df in zip(varnames, dfs):
                if varname not in d.variables:
                    dim_depth = var_to_depth_dim[varname]
                    if dim_depth not in d.dimensions:
                        # Add depth dimension
                        z = df.rename(columns={'in air': -1111}).columns.to_numpy(float)
                        d.createDimension(dim_depth, len(z))
                        var = d.createVariable(dim_depth, 'f4', (dim_depth,), fill_value=np.nan)
                        var[:] = z
                    # Initialize LUT
                    dimensions = tuple(['wavelength', dim_depth] + [dim for dim in d.dimensions.keys() if dim not in ['wavelength', 'depth', 'depthK', 'depth0']])  # Ensure dimension order is consistent with index
                    dimensions_sizes = tuple([d.dimensions[k].size for k in dimensions])
                    var = d.createVariable(varname, 'f4', dimensions, fill_value=np.nan)
                    var[:] = np.empty(dimensions_sizes, dtype=np.float32) * np.nan
                # Write data
                var = d.variables[varname]
                var[(slice(None), slice(None)) + index] = df.to_numpy(dtype=np.float32)


def write_lut(luts: Union[np.ndarray, List[np.ndarray]], dims: dict, constants: dict,
              varnames: Union[str, List[str]], filename: str):
    """
    Write n-dimensional lookup table to NetCDF file
    Protect critical section from KeyboardInterrupt to prevent data corruption.

    :param luts: lookup table(s)
    :param dims: dimensions
    :param constants: constants
    :param varnames: variables names to write in LUT
    :param filename: output filename
    :return:
    """
    if not isinstance(netCDF4, ModuleType):
        raise ModuleNotFoundError('write_netcdf requires the module netCDF4.')

    if isinstance(varnames, str):
        varnames = [v.strip() for v in varnames.split(',')] if ',' in varnames else [varnames]
    if isinstance(luts, np.ndarray):
        luts = [luts]
    if len(luts) != len(varnames):
        raise ValueError('Length of luts and varnames must be the same.')

    init_lut(filename, varnames, dims, constants)

    with delay_sigint():
        with netCDF4.Dataset(filename, 'a', format='NETCDF4') as d:
            for lut, varname in zip(luts, varnames):
                fill_value = np.nan if np.issubdtype(lut.dtype, np.floating) else None
                var = d.createVariable(varname, lut.dtype, tuple(dims.keys()), fill_value=fill_value)
                var[:] = lut


def read_lut(filename: str):
    """
    Read n-dimensional lookup table from NetCDF file

    :param filename: input filename
    :return: lut, dims, constants
    """
    if not isinstance(netCDF4, ModuleType):
        raise ModuleNotFoundError('read_netcdf requires the module netCDF4.')

    luts = []
    with netCDF4.Dataset(filename, 'r') as d:
        d.set_auto_mask(False)
        if 'varnames' in d.ncattrs():
            varnames = d.varnames.split(',')
        elif 'varname' in d.ncattrs():
            varnames = d.varname.split(',')
        else:
            raise ValueError('LUT file does not contain varnames attribute.')
        # Constants
        constants = {}
        for k in d.variables.keys():
            if k in varnames or k in d.dimensions:
                continue
            constants[k] = np.asarray(d.variables[k][:]).item()
            if d.variables[k].dtype == 'u1':
                constants[k] = bool(constants[k])
        # Dimensions
        dims = {}
        for dim_name in d[varnames[0]].dimensions:
            dims[dim_name] = d.variables[dim_name][:]
        # LUT
        for varname in varnames:
            luts.append(d.variables[varname][:])
    if len(luts) == 1:
        luts = luts[0]
    return luts, dims, constants


def merge_partial_luts(path_to_luts: list, path_to_merged_lut: str):
    """
    Merge multiple partial LUT NetCDF files into one LUT NetCDF file.
    Uses dimensions from the first LUT as reference and maps other LUTs to it.

    :param path_to_luts: list of input LUT NetCDF files
    :param path_to_merged_lut: output LUT NetCDF file
    :return:
    """

    # Get reference dimensions, constants, and variables from first LUT
    with netCDF4.Dataset(path_to_luts[0], 'r') as d:
        hash0 = d.id
        dimensions0 = {dim_name: d.variables[dim_name][:] for dim_name in d.dimensions.keys()}
        if 'varnames' in d.ncattrs():
            varnames = d.varnames.split(',')
        elif 'varname' in d.ncattrs():
            varnames = d.varname.split(',')
        else:
            raise ValueError('LUT file does not contain varnames attribute.')
        constants0 = {k: np.asarray(d.variables[k][:]).item() for k in d.variables.keys()
                      if k not in d.dimensions and k not in varnames}
        variables0 = {varname: d.variables[varname].dimensions for varname in varnames}

    # Check all LUTs have compatible hash and constants
    flag = False
    for f in path_to_luts[1:]:
        with netCDF4.Dataset(f, 'r') as d:
            if d.id != hash0:
                print(f'Warning: LUT hash mismatch in file {os.path.basename(f)}: {d.id} vs {hash0}')

            # Check constants
            constants = {k: np.asarray(d.variables[k][:]).item() for k in d.variables.keys()
                        if k not in d.dimensions and k not in varnames}
            if constants.keys() != constants0.keys():
                print(f'Warning: LUT constant keys mismatch in file {os.path.basename(f)}')
                flag = True
            else:
                for c in constants0.keys():
                    if constants[c] != constants0[c]:
                        print(f'Warning: LUT constant {c} mismatch in file {os.path.basename(f)}')
                        flag = True

            # Check dimensions
            dimensions = {dim_name: d.variables[dim_name][:] for dim_name in d.dimensions.keys()}
            for dim_name in dimensions.keys():
                if dim_name in dimensions0 and not np.array_equal(dimensions[dim_name], dimensions0[dim_name]):
                    print(f'Info: LUT dimension {dim_name} mismatch in file {os.path.basename(f)}')

            # Check core variable(s) dimensions
            for varname in varnames:
                if varname not in d.variables:
                    print(f'Info: LUT variable {varname} not found in file {os.path.basename(f)}, skipping')
                    continue
                if d.variables[varname].dimensions != variables0[varname]:
                    print(f'Warning: LUT variable {varname} dimension keys mismatch in file {os.path.basename(f)}')
                    flag = True
    if flag:
        raise ValueError('LUT files have mismatches, cannot merge. Please check warnings above.')

    # Copy first LUT as base
    if path_to_luts:
        shutil.copy(path_to_luts[0], path_to_merged_lut)

    # For each additional LUT, merge non-nan data into base LUT
    with netCDF4.Dataset(path_to_merged_lut, 'a') as d_dst:
        d_dst.set_auto_mask(False)
        for varname in varnames:
            var_dst = d_dst.variables[varname]
            data_dst = var_dst[:]
            var_dims = var_dst.dimensions

            for f in path_to_luts[1:]:
                with netCDF4.Dataset(f, 'r') as d_src:
                    d_src.set_auto_mask(False)
                    if varname not in d_src.variables:
                        continue
                    data_src = d_src.variables[varname][:]

                    # Build mapping from source dimensions to destination dimensions
                    dim_mappings = []
                    dimensions_match = True
                    for dim_idx, dim_name in enumerate(var_dims):
                        src_dim_vals = d_src.variables[dim_name][:]
                        dst_dim_vals = dimensions0[dim_name]

                        if np.array_equal(src_dim_vals, dst_dim_vals):
                            # Dimensions match exactly
                            dim_mappings.append(None)
                        else:
                            # Dimensions differ, need to map
                            dimensions_match = False
                            # Create mapping from source index to destination index
                            mapping = {}
                            for src_idx, src_val in enumerate(src_dim_vals):
                                # Find matching value in destination
                                dst_idx = np.where(np.isclose(dst_dim_vals, src_val, rtol=1e-7, atol=1e-9))[0]
                                if len(dst_idx) > 0:
                                    mapping[src_idx] = dst_idx[0]
                                else:
                                    print(f'Warning: {dim_name}={src_val} from {os.path.basename(f)} not found in reference LUT, skipping')
                            dim_mappings.append(mapping)

                    if dimensions_match:
                        # All dimensions match, direct merge
                        src_valid, dst_valid = ~np.isnan(data_src), ~np.isnan(data_dst)
                        # Check for conflicts
                        overlap_mask = src_valid & dst_valid
                        if np.any(overlap_mask) and not np.allclose(data_src[overlap_mask], data_dst[overlap_mask]):
                            print(f'Warning: LUT variable {varname} has different non-nan values in file {os.path.basename(f)}')
                        # Merge non-nan values from source LUT into destination LUT
                        data_dst[src_valid] = data_src[src_valid]
                    else:
                        # Vectorized merge: iterate only over mismatched dimensions
                        # Identify which dimensions differ
                        mismatched_dims = [i for i, mapping in enumerate(dim_mappings) if mapping is not None]
                        if not mismatched_dims:
                            # Should not reach here
                            raise RuntimeError("Unexpected state: dimensions_match is False but no mismatched dimensions found")
                        # Get shapes for iteration
                        mismatch_shapes = [data_src.shape[i] for i in mismatched_dims]
                        # Iterate only over mismatched dimensions
                        for mismatch_idx in np.ndindex(*mismatch_shapes):
                            # Build source and destination slices
                            src_slice = [slice(None)] * data_src.ndim
                            dst_slice = [slice(None)] * data_dst.ndim
                            # Map mismatched dimension indices
                            skip = False
                            for i, dim_idx in enumerate(mismatched_dims):
                                src_i = mismatch_idx[i]
                                if src_i in dim_mappings[dim_idx]:
                                    src_slice[dim_idx] = src_i
                                    dst_slice[dim_idx] = dim_mappings[dim_idx][src_i]
                                else:
                                    skip = True
                                    break
                            if skip:
                                # Source index does not have a matching destination index, skip this slice
                                continue
                            # Extract slices (vectorized over matched dimensions)
                            src_slice = tuple(src_slice)
                            dst_slice = tuple(dst_slice)
                            src_data = data_src[src_slice]
                            dst_data = data_dst[dst_slice]
                            # Check for conflicts
                            src_valid = ~np.isnan(src_data)
                            dst_valid = ~np.isnan(dst_data)
                            overlap_mask = src_valid & dst_valid
                            if np.any(overlap_mask) and not np.allclose(src_data[overlap_mask], dst_data[overlap_mask]):
                                print(f'Warning: LUT variable {varname} has different non-nan values at slice {dst_slice} in file {os.path.basename(f)}')
                            # Merge non-nan values (vectorized)
                            data_dst[dst_slice][src_valid] = src_data[src_valid]

            # Write data back to destination LUT
            var_dst[:] = data_dst


def rename_lut_dimension(path_to_lut: str, old_dim_name: str = 'depth', new_dim_name: str = 'depthK'):
    """
    Rename an LUT table by renaming the depth dimension.
    Creates a temporary file and replaces the original.

    :param path_to_lut: Path to LUT NetCDF file to modify
    :param old_dim_name: Old dimension name to replace (default: 'depth')
    :param new_dim_name: New dimension name (default: 'depthK')
    """
    if old_dim_name == new_dim_name:
        print(f'Old and new dimension names are the same ({old_dim_name}). No changes made.')
        return

    if isinstance(netCDF4, type(None)):
        raise ModuleNotFoundError('netCDF4 is required for this operation.')

    if not os.path.exists(path_to_lut):
        raise ValueError(f'LUT file not found: {path_to_lut}')

    # Create temporary file in same directory to ensure same filesystem
    temp_dir = os.path.dirname(path_to_lut)
    with tempfile.NamedTemporaryFile(dir=temp_dir, delete=False, suffix='.nc') as tmp:
        temp_path = tmp.name

    try:
        # Read source file
        with netCDF4.Dataset(path_to_lut, 'r') as src:
            src.set_auto_mask(False)

            # Check if old dimension exists
            if old_dim_name not in src.dimensions:
                print(f'{os.path.basename(path_to_lut)}: Dimension {old_dim_name} not found in LUT. No changes made.')
                os.remove(temp_path)
                return

            # Create new file with renamed dimension
            with netCDF4.Dataset(temp_path, 'w', format=src.data_model) as dst:
                # Copy global attributes
                for attr in src.ncattrs():
                    dst.setncattr(attr, src.getncattr(attr))

                # Create dimensions (with renamed old_dim_name)
                for dim_name, dim in src.dimensions.items():
                    new_name = new_dim_name if dim_name == old_dim_name else dim_name
                    dst.createDimension(new_name, dim.size)

                # Copy and rename variables
                for varname in src.variables.keys():
                    var_src = src.variables[varname]

                    # Update dimensions tuple
                    old_dims = var_src.dimensions
                    new_dims = tuple(new_dim_name if d == old_dim_name else d for d in old_dims)

                    # Rename the variable if it's the coordinate variable for the old dimension
                    new_varname = new_dim_name if varname == old_dim_name else varname

                    # Create new variable
                    fill_value = var_src._FillValue if hasattr(var_src, '_FillValue') else None
                    var_dst = dst.createVariable(new_varname, var_src.dtype, new_dims, fill_value=fill_value)

                    # Copy data
                    # Handle VLEN variables differently - they require integer indexing
                    if var_src.dtype == str:  # Object type (VLEN)
                        # For VLEN, copy element by element using integer indexing
                        if var_src.ndim == 0:
                            var_dst[()] = var_src[()]
                        else:
                            for idx in np.ndindex(var_src.shape):
                                var_dst[idx] = var_src[idx]
                    else:
                        # For regular variables, use slice notation
                        var_dst[:] = var_src[:]

                    # Copy attributes
                    for attr in var_src.ncattrs():
                        if attr in ['_FillValue', 'missing_value']:
                            continue  # Skip as attributes are handled by the createVariable parameter
                        var_dst.setncattr(attr, var_src.getncattr(attr))

        # Replace original file with temporary file
        shutil.move(temp_path, path_to_lut)

    except Exception as e:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise e
