from datetime import datetime, timezone
from hashlib import shake_128
import os
from types import ModuleType
from typing import Tuple

import numpy as np
import pandas as pd
try:
    import netCDF4
except ImportError:
    netCDF4 = None

from .. import __version__
from ..io import Hyrolight6Input
from ..utils import get_dtype, delay_sigint


def init_lut(path_to_lut: str, varname: str, dimensions: dict, constants: dict, lut_hash: str = None):
    """
    Initialize LUT NetCDF file with dimensions and constants.
    The main variable is not initialized (as required knowledge from HE60 output).

    :param path_to_lut:
    :param varname:
    :param dimensions:
    :param constants:
    :param lut_hash:
    :return:
    """
    if not isinstance(netCDF4, ModuleType):
        raise ModuleNotFoundError('write_netcdf requires the module netCDF4.')

    if os.path.isfile(path_to_lut):
        raise ValueError(f'LUT file already exists: {path_to_lut}')

    if lut_hash is None:
        lut_hash = shake_128((str(dimensions)+str(constants)).encode()).hexdigest(3)

    with delay_sigint():
        with netCDF4.Dataset(path_to_lut, 'w', format='NETCDF4') as d:
            # Global attributes
            d.title = f'Lookup Table of {varname} for case 1 waters generated by HydroLight6'
            d.description = 'Source code is the documentation.'
            d.conventions = 'CF-1.10,ACDD-1.3'
            d.id = f'he60_lut_{varname.lower()}_case1.{lut_hash}'
            d.naming_authority = 'HyperNavProjectOffice'
            d.source = 'HydroLight 6.0.1'
            d.date_created = f"{datetime.now().astimezone(timezone.utc).isoformat(timespec='seconds')}"
            d.product_version = __version__
            d.varname = varname

            # Constants
            constants0 = Hyrolight6Input().__dict__
            if constants is not None:
                constants0.update(constants)
            for k in ['output_depths', 'output_dir', 'wavelength_start', 'wavelength_stop', 'wavelength_step'] + list(
                    dimensions.keys()):
                del constants0[k]
            for k, v in constants0.items():
                dtype, fill_value = get_dtype(v)
                var = d.createVariable(k, dtype, fill_value=fill_value)
                var[...] = v

            # Dimensions
            for k, v in dimensions.items():
                d.createDimension(k, len(v))
                dtype, fill_value = get_dtype(v)
                var = d.createVariable(k, dtype, (k,), fill_value=fill_value)
                var[:] = v


def write_chunk_to_lut(df: pd.DataFrame, index: Tuple[int], varname: str, path_to_lut: str):
    """
    Write output of one HydroLight 6.0 simulation to LUT. Assumes chunk is consistent with LUT dimensions and index.
    Automatically initialize wavelength and depth dimensions if not already present in LUT.
    Initialize LUT variable if not already present, otherwise will write to existing variable.
    Protect critical section from KeyboardInterrupt to prevent data corruption.

    :param df: DataFrame with output variable, indexed by wavelength and depth
    :param index: LUT index corresponding to the input configuration of df
    :param varname: variable name to write in LUT
    :param path_to_lut: path to LUT NetCDF file
    :return:
    """
    with delay_sigint():
        with netCDF4.Dataset(path_to_lut, 'a') as d:
            if varname not in d.variables:
                # Initialize output dimensions if needed
                if 'wl' not in d.dimensions:
                    # Add wavelength dimension
                    wl = df.index.to_numpy(int)
                    d.createDimension('wavelength', len(wl))
                    var = d.createVariable('wavelength', 'u2', ('wavelength',))
                    var[:] = wl
                if 'depth' not in d.dimensions:
                    # Add depth dimension
                    z = df.rename(columns={'in air': -1111}).columns.to_numpy(float)
                    d.createDimension('depth', len(z))
                    var = d.createVariable('depth', 'f4', ('depth',), fill_value=np.nan)
                    var[:] = z
                # Initialize LUT
                dimensions = tuple(['wavelength', 'depth'] + [dim for dim in d.dimensions.keys() if dim not in ['wavelength', 'depth']])  # Ensure dimension order is consistent with index
                dimensions_sizes = tuple([d.dimensions[k].size for k in dimensions])
                var = d.createVariable(varname, 'f4', dimensions, fill_value=np.nan)
                var[:] = np.empty(dimensions_sizes, dtype=np.float32) * np.nan
            # Write data
            var = d.variables[varname]
            var[(slice(None), slice(None)) + index] = df.to_numpy(dtype=np.float32)


def write_lut(lut: np.ndarray, dims: dict, constants: dict, varname: str, filename: str):
    """
    Write n-dimensional lookup table to NetCDF file
    Protect critical section from KeyboardInterrupt to prevent data corruption.

    :param lut: lookup table
    :param dims: dimensions
    :param constants: constants
    :param varname: variable name to write in LUT
    :param filename: output filename
    :return:
    """
    if not isinstance(netCDF4, ModuleType):
        raise ModuleNotFoundError('write_netcdf requires the module netCDF4.')

    init_lut(filename, varname, dims, constants)

    with delay_sigint():
        with netCDF4.Dataset(filename, 'a', format='NETCDF4') as d:
            # LUT
            fill_value = np.nan if np.issubdtype(lut.dtype, np.floating) else None
            var = d.createVariable(varname, lut.dtype, tuple(dims.keys()), fill_value=fill_value)
            var[:] = lut


def read_lut(filename: str):
    """
    Read n-dimensional lookup table from NetCDF file

    :param filename: input filename
    :return: lut, dims, constants
    """
    if not isinstance(netCDF4, ModuleType):
        raise ModuleNotFoundError('read_netcdf requires the module netCDF4.')

    with netCDF4.Dataset(filename, 'r') as d:
        d.set_auto_mask(False)
        varname = d.varname
        # Constants
        constants = {}
        for k in d.variables.keys():
            if k == varname or k in d.dimensions:
                continue
            constants[k] = np.asarray(d.variables[k][:]).item()
            if d.variables[k].dtype == 'u1':
                constants[k] = bool(constants[k])
        # Dimensions
        dims = {}
        for dim_name in d.dimensions.keys():
            dims[dim_name] = d.variables[dim_name][:]
        # LUT
        lut = d.variables[varname][:]

    return lut, dims, constants
